/**
 * Copyright 2013 Davide Nunes
 * Authors : Davide Nunes <davex.pt@gmail.com>
 * Website : http://davidenunes.com 
 * 
 * DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS HEADER.
 * 
 * This file is part of the b-have sweeper library.
 * 
 * The b-have sweeper library is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * The b-have sweeper library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with the b-have network library.  
 * If not, see <http://www.gnu.org/licenses/gpl.html>.
 */
package org.bhave.sweeper;

import org.apache.commons.configuration.Configuration;

/**
 * Interface for Parameter Sweeps. These are data structures capable of storing
 * and iterating over single or aggregate parameter sweeps. Each parameter sweep
 * is uniquely identified according to its content so two identical parameter
 * sweeps should return true with equals.
 *
 * @author Davide Nunes
 */
public interface ParameterSweep extends Iterable<Configuration> {

    /**
     * Returns the parameter name associated with this sweep.
     *
     * @return a String with the parameter name
     */
    String getParameterName();

    /**
     * Returns the size of the parameter sweep, in other words, the number of
     * possible configuration values generated by its iterator.
     */
    int size();
}
