package org.bhave.sweeper;

import org.apache.commons.configuration.Configuration;

/**
 * Interface for Parameter Sweeps. These are data structures capable of storing
 * and iterating over single or aggregate parameter sweeps. Each parameter sweep
 * is uniquely identified according to its content so two identical parameter
 * sweeps should return true with equals.
 *
 * @author Davide Nunes
 */
public interface ParameterSweep extends Iterable<Configuration> {

    /**
     * Returns the parameter name associated with this sweep.
     *
     * @return a String with the parameter name
     */
    String getParameterName();

    /**
     * Returns the size of the parameter sweep, in other words, the number of
     * possible configuration values generated by its iterator.
     */
    int size();
}
